name: Publish Package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.2.0
        with:
          node-version: '22.x'

      - name: Cache npm dependencies
        uses: actions/cache@v3.4.2
        id: cache-npm
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install project dependencies
        if: steps.cache-npm.outputs.cache-hit != 'true'
        run: npm install

      - name: Build Angular lib for production
        run: npm run build @redkhat/timepicker

      - name: Build demo
        run: npm run build-gh

      - name: Rename index.html for routing
        run: mv dist/demo/browser/index.html dist/demo/browser/404.html

      # Deploy demo to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4.1.0
        with:
          build_dir: dist/demo/browser/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Publish to npm
      - name: Publish to npm
        run: |
          npm config set '//registry.npmjs.org/:_authToken' ${{ secrets.NPM_TOKEN }}
          npm publish dist/redkhat/timepicker --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Publish to GitHub Packages
      - name: Publish to GitHub Packages
        run: |
          npm config set '//npm.pkg.github.com/:_authToken' ${{ secrets.GITHUB_TOKEN }}
          npm publish dist/redkhat/timepicker --registry=https://npm.pkg.github.com
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
